UPDATE role
SET name = CASE code
    WHEN 'SALES' THEN '销售'
    WHEN 'SALES_MANAGER' THEN '销售主管'
    WHEN 'PRESALES_TECH' THEN '售前技术'
    WHEN 'PROJECT_MANAGER' THEN '项目经理'
    WHEN 'OPERATIONS_VIEWER' THEN '运营管理'
    WHEN 'FINANCE_VIEWER' THEN '财务查看'
    WHEN 'EXECUTIVE_VIEWER' THEN '高级管理'
    WHEN 'SYSTEM_ADMIN' THEN '系统管理员'
    ELSE name
END
WHERE code IN (
    'SALES',
    'SALES_MANAGER',
    'PRESALES_TECH',
    'PROJECT_MANAGER',
    'OPERATIONS_VIEWER',
    'FINANCE_VIEWER',
    'EXECUTIVE_VIEWER',
    'SYSTEM_ADMIN'
);
